import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
// import { useEffect } from "react";

// import Image from "next/image";
// import { Carousel, Button } from "react-bootstrap";

function Layout({ title, children }) {
  const myStyle = {
    float: "right",
  };

  // const handleToggleAnswer = () => {
  //   setShowAnswer(!showAnswer);
  // };
  return (
    <>
      <Head>
        <title> {title ? title + " - Pro Resume" : "Pro Resume"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />

        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-jxttucUCuVqXam5z5c4i/QRTPZp0W1x+fKvRfTw1EJyHXfACWmH8MIvKMrZCmFZP+oW2fd8A1NGb5dS7eINt1Q=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        /> */}

        <link rel="stylesheet" href="./css/owl.carousel.min.css" />
        {/* <link rel="stylesheet" href="./css/owl.theme.default.min.css"/> */}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="jquery.min.js"></script>
        <script src="./js/owl.carousel.min.js"></script>
        <script src="./js/common.js"></script>
      </Head>

      <div>
        <header id="header">
          <div class="head-main">
            <div class="container">
              <div class="row">
                <div class="col-sm-3">
                  <div class="header-mini">
                    <Link href="/" legacyBehavior>
                      <a>
                        <img src="/images/logo.png" class="head-logo" alt="" />
                      </a>
                    </Link>
                  </div>
                </div>
                <div class="col-sm-9">
                  <nav class="nav">
                    <div class="navbar-header">
                      <div class="collapse-nav">
                        <button
                          class="collapse-button"
                          type="button"
                          id="toggle-button"
                        >
                          <span class="icon-bar"></span>

                          <span class="icon-bar"></span>

                          <span class="icon-bar"></span>
                        </button>
                      </div>
                    </div>
                    <ul class="menu">
                      <li>
                        <Link href="/" legacyBehavior>
                          <a>
                            Services{" "}
                            <i
                              class="fa fa-chevron-down small"
                              aria-hidden="true"
                            ></i>
                          </a>
                        </Link>

                        <ul class="submenu">
                          <li>
                            <Link href="/services/resume" legacyBehavior>
                              <a>Resume Writing</a>
                            </Link>
                          </li>
                          <li>
                            <Link href="/services/professional" legacyBehavior>
                              <a>Professional Letter</a>
                            </Link>{" "}
                          </li>
                          <li>
                            <Link href="/services/linkedin" legacyBehavior>
                              <a>Linkedin Makeover</a>
                            </Link>{" "}
                          </li>
                          <li>
                            <Link href="/interview" legacyBehavior>
                              <a>Interview Preperation</a>
                            </Link>{" "}
                          </li>
                        </ul>
                      </li>
                      <li>
                        <Link href="/about-us" legacyBehavior>
                          <a>About Us</a>
                        </Link>{" "}
                      </li>

                      <li>
                        <Link href="/pricing" legacyBehavior>
                          <a>Prices </a>
                        </Link>
                      </li>
                      <li>
                        <Link href="/" legacyBehavior>
                          <a class="btn btn-outline-secondary me-3">
                            Make a Bundle
                          </a>
                        </Link>{" "}
                      </li>
                      <li>
                        <Link href="/" legacyBehavior>
                          <a class="btn btn-primary-custom">Custom Bundle</a>
                        </Link>{" "}
                      </li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
          </div>
        </header>
        <main>{children}</main>

        <footer id="footer">
          <div class="container">
            <div class="row border-bottom">
              <div class="col-sm-2">
                <div class="footer-logo">
                  <Link href="/" legacyBehavior>
                    <a></a>
                  </Link>{" "}
                </div>
              </div>
              <div class="col-sm-2 offset-sm-8">
                <ul class="social-footer">
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>
                        <img src="/images/Fb.png" alt="fb" />
                      </a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>
                        <img src="/images/Twetter.png" alt="fb" />{" "}
                      </a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>
                        <img src="/images/LinkedIn.png" alt="fb" />
                      </a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>
                        <img src="/images/youtube.png" alt="fb" />
                      </a>
                    </Link>{" "}
                  </li>
                </ul>
              </div>
            </div>
            <div class="row mt-5 border-bottom">
              <div class="col-sm-4">
                <h4>Services</h4>
                <ul>
                  <li>
                    <Link href="/services/resume" legacyBehavior>
                      <a>Resume Writing</a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/services/linkedin" legacyBehavior>
                      <a>Linkedin Makeover</a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/services/professional" legacyBehavior>
                      <a>Professional CV Writing</a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/services/interview" legacyBehavior>
                      <a>Interview Preperation</a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>Cover Letter Writing</a>
                    </Link>{" "}
                  </li>
                </ul>
              </div>
              <div class="col-sm-4">
                <h4>Learn More</h4>
                <ul>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>Help Center</a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>Career Advise Blog</a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>Customer Success Stories</a>
                    </Link>{" "}
                  </li>
                </ul>
              </div>
              <div class="col-sm-4">
                <h4>Company</h4>
                <ul>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>About Us</a>
                    </Link>{" "}
                  </li>
                  <li>
                    <Link href="/" legacyBehavior>
                      <a>Contact Us</a>
                    </Link>{" "}
                  </li>
                </ul>
              </div>
            </div>
            <div class="mini-footer">
              <small>
                Copyright by Careergenics | All rights reserverd
                <span style={myStyle}>
                  Our Privacy and Personal Data Protection Policy | Terms and
                  Conditions of Use
                </span>
              </small>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}

export default Layout;
